### ISSUE TITLE
Single File Components 'No data to display'

### ISSUE THREAD

**Issue by dgriego** [fusioncharts/vue-fusioncharts#5] opened 2017-11-29 21:57 UTC
I'm using vue-fusioncharts with a single file component structure (utilizing webpack).  I've followed the instructions on how to include fusioncharts in the app (https://www.fusioncharts.com/vue-fusioncharts/) and continue to get 'No data to display'.  The only thing unique that I'm doing, different from the examples, is that the data is being included within a component and not on the Vue instance itself..

the main.js file:
```
import Vue from 'vue';
import VueFusionCharts from 'vue-fusioncharts';
import FusionCharts from 'fusioncharts';
import Charts from 'fusioncharts/fusioncharts.charts';
import App from './App';
import router from './router';
import store from './store';

// resolve charts dependency
Charts(FusionCharts);

// register VueFusionCharts component
Vue.use(VueFusionCharts);

// Require the main Sass manifest file
require('./assets/sass/main.sass');

Vue.config.productionTip = false;

/* eslint-disable no-new */
new Vue({
  el: '#app',
  store, // inject store to all children
  router,
  template: '<App/>',
  components: { App },
});
```

the component file
```
...
    fusioncharts(:type='type', :width='width', :height='height', :dataFormat='dataFormat', :dataSource='dataSource')
</template>

<script>
const myDataSource = {
  'chart': {
    'caption': 'Age profile of website visitors',
    'subcaption': 'Last Year',
    'theme': 'ocean',
  },
  'data': [
    {
      'label': 'Teenage',
      'value': '1250400',
    },
    {
      'label': 'Adult',
      'value': '1463300',
    },
    {
      'label': 'Mid-age',
      'value': '1050700',
    },
    {
      'label': 'Senior',
      'value': '491000',
    },
  ],
};

export default {
  name: 'track-progress',
  data() {
    return {
      type: 'column2d',
      width: '500',
      height: '300',
      dataFormat: 'json',
      dataSource: myDataSource,
    };
  },
};
</script>
...
```

I've looked at similar issues, but no luck and so far no solution regarding single file components.. any help would be appreciated!

**Comment by cschweda** [comment] 2017-12-15 20:10
Any resolution on this? I'm seeing same issue.

**Comment by ariyankhan** [comment] 2017-12-17 07:23
@dgriego,  @cschweda 
Use property names of `<fusioncharts>` component in lowercase letter e.g. use `dataformat` instead of `dataFormat` and use `datasource` instead of `dataSource`.

So, th template will be:
```html
<template>
   <fusioncharts
        :type="type"
        :width="width"
        :height="height"
        :dataformat="dataFormat"
        :datasource="dataSource">
    </fusioncharts>
</template>
```
let me know if you face any problem.

**Comment by cschweda** [comment] 2017-12-18 14:48
Nope, still not working.

Here's a sample repo:

https://github.com/ICJIA/fusioncharts01

```
git clone https://github.com/ICJIA/fusioncharts01.git
cd fusioncharts01
yarn install
yarn run dev
```

Any insight to the 'No Data to Display' error would be much appreciated.

**Comment by ariyankhan** [comment] 2017-12-19 05:24
@cschweda 

If you want to use `FusionCharts` maps then you need to import fusioncharts maps modules as follows:
```javascript
// The Vue build version to load with the `import` command
// (runtime-only or standalone) has been set in webpack.base.conf with an alias.
import Vue from 'vue'
import App from './App'
import router from './router'
import VueFusionCharts from 'vue-fusioncharts';

// import FusionCharts modules and resolve dependency
import FusionCharts from 'fusioncharts';
import Charts from 'fusioncharts/fusioncharts.charts';
import Maps from 'fusioncharts/fusioncharts.maps';
import USAMap from 'fusioncharts/maps/fusioncharts.usa'; // import it for maps/usa chart type
import WorldMap from 'fusioncharts/maps/fusioncharts.world'; // import it for maps/world chart type

// resolve charts dependency
Charts(FusionCharts);
Maps(FusionCharts);
USAMap(FusionCharts);
WorldMap(FusionCharts);

// register VueFusionCharts component
Vue.use(VueFusionCharts, FusionCharts);

Vue.config.productionTip = false

/* eslint-disable no-new */
new Vue({
    el: '#app',
    router,
    template: '<App/>',
    components: { App }
})
```

**Comment by cschweda** [comment] 2017-12-19 19:47
Thanks! This works.

My last issue: is there a way to pass the Vue instance into the ```entityClick``` method on the chart?

In other words, my map is defined like:\

```
 <fusioncharts
          type="illinois"
          width="600"
          height="700"
          dataformat="json"
          :datasource="fm"
          :events="events"
          ></fusioncharts>
```
And my ```events``` is in the Vue instance as:

```
...
data() {
            return {
                events: {
                    entityClick: function entityClick(evt, data) {
                        console.log(this)
                    }
                },
...
```
But I can't refrence any of the Vue methods I've defined. 

```this``` in the ```entityClick``` function is the chart object -- not the Vue object.

**Comment by cschweda** [comment] 2017-12-21 15:22
Everything working now. Thank you!

**Comment by ariyankhan** [comment] 2017-12-21 17:01
Closing issue due to the problem is solved.

**Closed by ariyankhan** 2017-12-21 17:01 UTC
